name: Deploy Vite App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Kill and remove any existing container
          docker stop vite-app || true
          docker rm vite-app || true

          # Navigate or clone the repo fresh (choose only one approach)
          cd ~/vite-deploy || git clone https://github.com/${{ github.repository }} ~/vite-deploy && cd ~/vite-deploy

          # Pull latest code
          git pull origin main

          # Build Docker image
          docker build -t vite-app .

          # Run Docker container
          docker run -d -p 3000:4173 --name vite-app vite-app
        EOF
